// Build script: transpile the uor-addr-wasm Component Model artifact
// at ../../target/wasm32-wasip2/release/uor_addr_wasm.wasm into ES
// module + TypeScript glue under ./dist/.
//
// In CI / publish flow, the .wasm artifact is already produced by the
// `wasm` job in .github/workflows/release.yml and dropped at the same
// path. Locally, `cargo build -p uor-addr-wasm --target wasm32-wasip2
// --release` produces it from the workspace root.

import { execSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..", "..", "..");
const wasmPath = join(root, "target", "wasm32-wasip2", "release", "uor_addr_wasm.wasm");
const distDir = resolve(__dirname, "..", "dist");

if (!existsSync(wasmPath)) {
  console.error(`error: expected wasm artifact at ${wasmPath}`);
  console.error("       run: cargo build -p uor-addr-wasm --target wasm32-wasip2 --release");
  process.exit(1);
}

mkdirSync(distDir, { recursive: true });

console.log("transpiling uor_addr_wasm.wasm via jco…");
execSync(
  `npx jco transpile "${wasmPath}" --out-dir "${distDir}" --name uor-addr --no-typescript`,
  { stdio: "inherit", cwd: resolve(__dirname, "..") }
);

// Generate a TypeScript ambient declaration matching the WIT exports
// (one *-address function per realization). jco's --no-typescript flag
// suppresses its own .d.ts emit so we ship a hand-written one that
// matches the public surface 1:1.
const dts = `// Generated by bindings/npm/scripts/build.mjs — do not edit by hand.
// Mirrors crates/uor-addr-wasm/wit/uor-addr.wit.

/** ASCII \`sha256:<64hex>\` κ-label — exactly 71 bytes. */
export type KappaLabel = string;

/** Failure modes from any realization's address function. */
export type AddressError =
  | "invalid-input"
  | "too-large"
  | "pipeline-failure";

/** Failure modes from \`Grounded.verify()\` — 1:1 with the WIT
 * \`verify-error\` variant. All five are defensive against substrate
 * corruption; unreachable for a \`Grounded\` minted through this
 * binding. */
export type VerifyError =
  | "empty-trace"
  | "out-of-order-event"
  | "zero-target"
  | "non-contiguous-steps"
  | "capacity-exceeded";

/** Opaque foreign-managed witness handle to a Rust-side
 * \`Grounded<AddressLabel>\` value carrying the ψ-pipeline's emitted
 * derivation.
 *
 * TC-05 conformance: every Grounded produced by a
 * \`*AddressWithWitness\` call replays through \`verify()\` to a
 * κ-label byte-identical to the one \`kappaLabel()\` reports
 * (QS-05 replay equivalence — bit-identical round-trip).
 *
 * Lifetime: in-process state held by the Component Model runtime.
 * Cross-process attestation is not supported — for that, persist the
 * κ-label itself and re-mint at the verifier side. */
export interface Grounded {
  /** Return the 71-byte ASCII κ-label this Grounded carries. */
  kappaLabel(): KappaLabel;
  /** Return the 32-byte SHA-256 content fingerprint. */
  contentFingerprint(): Uint8Array;
  /** Replay the derivation through \`prism_verify::certify_from_trace\`
   * and return the recovered κ-label. SHA-256 is **not** re-invoked. */
  verify(): KappaLabel;
}

export interface Kappa {
  /** RFC 8259 JSON under RFC 8785 JCS + Unicode NFC. */
  jsonAddress(input: Uint8Array): KappaLabel;
  /** Rivest 1997 canonical S-expressions. */
  sexpAddress(input: Uint8Array): KappaLabel;
  /** W3C XML-C14N 1.1 (subset). */
  xmlAddress(input: Uint8Array): KappaLabel;
  /** ITU-T X.690 DER. */
  asn1Address(input: Uint8Array): KappaLabel;
  /** UOR-Framework Amendment 43 §2 ring elements. */
  ringAddress(input: Uint8Array): KappaLabel;
  /** CCMAS canonical AST. */
  codemoduleAddress(input: Uint8Array): KappaLabel;
  /** schema.org/Photograph admission + JSON canonicalization. */
  schemaPhotoAddress(input: Uint8Array): KappaLabel;
  /** schema.org/Article admission + JSON canonicalization. */
  schemaDocumentAddress(input: Uint8Array): KappaLabel;
  /** in-toto Statement v1 admission + JSON canonicalization. */
  schemaCodemoduleSignedAddress(input: Uint8Array): KappaLabel;

  // ── Witness-bearing variants (TC-05 cross-language replay) ──

  /** JSON realization; returns a verifiable [\`Grounded\`] witness. */
  jsonAddressWithWitness(input: Uint8Array): Grounded;
  /** S-expression realization; returns a verifiable witness. */
  sexpAddressWithWitness(input: Uint8Array): Grounded;
  /** XML realization; returns a verifiable witness. */
  xmlAddressWithWitness(input: Uint8Array): Grounded;
  /** ASN.1 realization; returns a verifiable witness. */
  asn1AddressWithWitness(input: Uint8Array): Grounded;
  /** Ring realization; returns a verifiable witness. */
  ringAddressWithWitness(input: Uint8Array): Grounded;
  /** Code-module realization; returns a verifiable witness. */
  codemoduleAddressWithWitness(input: Uint8Array): Grounded;
  /** schema.org/Photograph; returns a verifiable witness. */
  schemaPhotoAddressWithWitness(input: Uint8Array): Grounded;
  /** schema.org/Article; returns a verifiable witness. */
  schemaDocumentAddressWithWitness(input: Uint8Array): Grounded;
  /** in-toto Statement v1; returns a verifiable witness. */
  schemaCodemoduleSignedAddressWithWitness(input: Uint8Array): Grounded;
}

export const kappa: Kappa;
`;
writeFileSync(join(distDir, "uor-addr.d.ts"), dts);

console.log(`wrote ${distDir}/uor-addr.d.ts`);
console.log("done.");
