// Build script: transpile the uor-addr-wasm Component Model artifact
// at ../../target/wasm32-wasip2/release/uor_addr_wasm.wasm into ES
// module + TypeScript glue under ./dist/.
//
// In CI / publish flow, the .wasm artifact is already produced by the
// `wasm` job in .github/workflows/release.yml and dropped at the same
// path. Locally, `cargo build -p uor-addr-wasm --target wasm32-wasip2
// --release` produces it from the workspace root.

import { execSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..", "..", "..");
const wasmPath = join(root, "target", "wasm32-wasip2", "release", "uor_addr_wasm.wasm");
const distDir = resolve(__dirname, "..", "dist");

if (!existsSync(wasmPath)) {
  console.error(`error: expected wasm artifact at ${wasmPath}`);
  console.error("       run: cargo build -p uor-addr-wasm --target wasm32-wasip2 --release");
  process.exit(1);
}

mkdirSync(distDir, { recursive: true });

console.log("transpiling uor_addr_wasm.wasm via jco…");
execSync(
  `npx jco transpile "${wasmPath}" --out-dir "${distDir}" --name uor-addr --no-typescript`,
  { stdio: "inherit", cwd: resolve(__dirname, "..") }
);

// Generate a TypeScript ambient declaration matching the WIT exports
// (one *-address function per realization). jco's --no-typescript flag
// suppresses its own .d.ts emit so we ship a hand-written one that
// matches the public surface 1:1.
const dts = `// Generated by bindings/npm/scripts/build.mjs — do not edit by hand.
// Mirrors crates/uor-addr-wasm/wit/uor-addr.wit.

/** ASCII \`sha256:<64hex>\` κ-label — exactly 71 bytes. */
export type KappaLabel = string;

/** Failure modes from any realization's address function. */
export type AddressError =
  | "invalid-input"
  | "too-large"
  | "pipeline-failure";

export interface AddressResult {
  /** The 71-byte κ-label on success. */
  tag: "ok";
  val: KappaLabel;
}

export interface AddressFailure {
  tag: "err";
  val: AddressError;
}

export type AddressOutcome = AddressResult | AddressFailure;

export interface Kappa {
  /** RFC 8259 JSON under RFC 8785 JCS + Unicode NFC. */
  jsonAddress(input: Uint8Array): KappaLabel;
  /** Rivest 1997 canonical S-expressions. */
  sexpAddress(input: Uint8Array): KappaLabel;
  /** W3C XML-C14N 1.1 (subset). */
  xmlAddress(input: Uint8Array): KappaLabel;
  /** ITU-T X.690 DER. */
  asn1Address(input: Uint8Array): KappaLabel;
  /** UOR-Framework Amendment 43 §2 ring elements. */
  ringAddress(input: Uint8Array): KappaLabel;
  /** CCMAS canonical AST. */
  codemoduleAddress(input: Uint8Array): KappaLabel;
  /** schema.org/Photograph admission + JSON canonicalization. */
  schemaPhotoAddress(input: Uint8Array): KappaLabel;
  /** schema.org/Article admission + JSON canonicalization. */
  schemaDocumentAddress(input: Uint8Array): KappaLabel;
  /** in-toto Statement v1 admission + JSON canonicalization. */
  schemaCodemoduleSignedAddress(input: Uint8Array): KappaLabel;
}

export const kappa: Kappa;
`;
writeFileSync(join(distDir, "uor-addr.d.ts"), dts);

console.log(`wrote ${distDir}/uor-addr.d.ts`);
console.log("done.");
