/* uor-addr-c — C ABI bindings for the uor-addr crate.
* Auto-generated by cbindgen. Do not edit by hand.
*
* Apache-2.0 — https://github.com/UOR-Foundation/uor-addr
*/

#ifndef UOR_ADDR_H
#define UOR_ADDR_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// σ-axis selector for the `*_with_hash` entry points: SHA-256 (default).
#define UOR_ADDR_HASH_SHA256 0

// σ-axis selector: BLAKE3.
#define UOR_ADDR_HASH_BLAKE3 1

// σ-axis selector: SHA3-256 (FIPS 202).
#define UOR_ADDR_HASH_SHA3_256 2

// σ-axis selector: Keccak-256 (pre-FIPS padding).
#define UOR_ADDR_HASH_KECCAK256 3

// Success.
#define UOR_ADDR_OK 0

// `input == NULL && input_len > 0`, or `out_label == NULL`.
#define UOR_ADDR_ERR_NULL_POINTER -1

// `out_label_len < UOR_ADDR_LABEL_BYTES`.
#define UOR_ADDR_ERR_BUFFER_TOO_SMALL -2

// Input failed the realization's host-boundary parser.
#define UOR_ADDR_ERR_INVALID_INPUT -3

// **Reserved** — never returned under ADR-060 (inputs are unbounded;
// the per-realization size/count caps were removed). Retained so
// existing `-4` handlers in downstream C consumers keep compiling.
#define UOR_ADDR_ERR_TOO_LARGE -4

// Defensive — substrate-level pipeline failure.
#define UOR_ADDR_ERR_PIPELINE -5

// Unknown σ-axis selector passed to a `*_with_hash` entry point (not one
// of the `UOR_ADDR_HASH_*` constants).
#define UOR_ADDR_ERR_UNKNOWN_HASH -6

// Verify-error codes — 1:1 with WIT `verify-error` variants. **Reserved
// forward-compat vocabulary**: under ADR-060 [`uor_addr_grounded_verify`]
// re-certifies through the owned witness ([`uor_addr::AddressWitness::verify`])
// and returns `UOR_ADDR_OK` or `UOR_ADDR_ERR_PIPELINE` only — the
// granular replay-failure codes below are retained for error-code
// stability and a future stricter verifier, and are unreachable for a
// handle the C ABI itself minted.
#define UOR_ADDR_ERR_VERIFY_EMPTY_TRACE -10

#define UOR_ADDR_ERR_VERIFY_OUT_OF_ORDER_EVENT -11

#define UOR_ADDR_ERR_VERIFY_ZERO_TARGET -12

#define UOR_ADDR_ERR_VERIFY_NON_CONTIGUOUS_STEPS -13

#define UOR_ADDR_ERR_VERIFY_CAPACITY_EXCEEDED -14

// Opaque handle to a Rust-side `AddressOutcome` carrying a sealed
// `Grounded<AddressLabel>` witness. Construct via any of the
// `uor_addr_<realization>_with_witness` functions; release via
// [`uor_addr_grounded_free`].
//
// **Lifetime**: the handle is valid until `uor_addr_grounded_free`
// is called. Calling any `uor_addr_grounded_*` accessor on a freed
// handle is undefined behaviour. The witness lives only in the
// process that minted it — there is no cross-process serialization
// (the underlying `Trace<256>` constructor is `pub(crate)` in
// `uor-foundation`).
typedef struct UorAddrGrounded {
  AddressOutcome<71> outcome;
} UorAddrGrounded;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Wire-format κ-label byte width under the default σ-axis (sha256) —
// `len("sha256:") + 64 = 71`.
extern const uintptr_t UOR_ADDR_LABEL_BYTES;

// Widest κ-label byte width across the admissible σ-axes (keccak256 →
// `len("keccak256:") + 64 = 74`). A `*_with_hash` output buffer sized to
// this fits every algorithm.
extern const uintptr_t UOR_ADDR_MAX_LABEL_BYTES;

// JSON realization (RFC 8785 JCS + Unicode NFC + SHA-256).
//
// # Safety
//
// - `input` must be null (with `input_len == 0`) or readable for
//   `input_len` bytes.
// - `out_label` must be writable for at least `out_label_len` bytes.
// - `out_written` if non-null must point to a writable `size_t`.
int32_t uor_addr_json(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// S-expression realization (Rivest 1997 canonical form + SHA-256).
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_sexp(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// XML realization (W3C XML-C14N 1.1 subset + SHA-256).
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_xml(const uint8_t *input,
                     uintptr_t input_len,
                     uint8_t *out_label,
                     uintptr_t out_label_len,
                     uintptr_t *out_written);

// ASN.1 realization (ITU-T X.690 DER + SHA-256).
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_asn1(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// Ring realization (UOR-Framework Amendment 43 §2 + SHA-256).
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_ring(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// Code-module realization (CCMAS canonical AST + SHA-256).
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_codemodule(const uint8_t *input,
                            uintptr_t input_len,
                            uint8_t *out_label,
                            uintptr_t out_label_len,
                            uintptr_t *out_written);

// schema.org/Photograph descendant — admits only schema.org/Photograph
// JSON-LD inputs; routes canonical form through the JSON realization.
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_schema_photo(const uint8_t *input,
                              uintptr_t input_len,
                              uint8_t *out_label,
                              uintptr_t out_label_len,
                              uintptr_t *out_written);

// schema.org/Article descendant — admits only schema.org/Article
// JSON-LD inputs (plus subtypes); routes canonical form through JSON.
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_schema_document(const uint8_t *input,
                                 uintptr_t input_len,
                                 uint8_t *out_label,
                                 uintptr_t out_label_len,
                                 uintptr_t *out_written);

// in-toto Statement v1 descendant — admits only in-toto Statement v1
// JSON envelopes (sigstore / SLSA / SCAI / SPDX SBOM predicates).
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_schema_codemodule_signed(const uint8_t *input,
                                          uintptr_t input_len,
                                          uint8_t *out_label,
                                          uintptr_t out_label_len,
                                          uintptr_t *out_written);

// GGUF v3 realization (spec-canonical flat Merkle skeleton + SHA-256).
//
// The κ-label binds every metadata byte and every tensor weight (the
// latter via streamed per-tensor digests). Under ADR-060 the canonical
// form is the full flat skeleton (no two-level commitment); KV / tensor
// counts and value widths are unbounded.
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_gguf(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// ONNX IR v13 realization (protobuf-canonical commitment + SHA-256).
//
// The κ-label binds the graph structure (nodes in topological order),
// initializer weights, and metadata. Uses the crate's `OnnxAddrBounds`
// encoding profile.
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_onnx(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// CBOR realization (RFC 8949 §4.2 deterministic encoding + SHA-256).
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_cbor(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// json realization with a caller-selected σ-axis (`UOR_ADDR_HASH_*`).
//
// # Safety
//
// Same pointer rules as [`uor_addr_json`]; `out_label` must be writable
// for at least `UOR_ADDR_MAX_LABEL_BYTES` bytes.
int32_t uor_addr_json_with_hash(uint8_t algo,
                                const uint8_t *input,
                                uintptr_t input_len,
                                uint8_t *out_label,
                                uintptr_t out_label_len,
                                uintptr_t *out_written);

// sexp realization with a caller-selected σ-axis (`UOR_ADDR_HASH_*`).
//
// # Safety
//
// Same pointer rules as [`uor_addr_json`]; `out_label` must be writable
// for at least `UOR_ADDR_MAX_LABEL_BYTES` bytes.
int32_t uor_addr_sexp_with_hash(uint8_t algo,
                                const uint8_t *input,
                                uintptr_t input_len,
                                uint8_t *out_label,
                                uintptr_t out_label_len,
                                uintptr_t *out_written);

// xml realization with a caller-selected σ-axis (`UOR_ADDR_HASH_*`).
//
// # Safety
//
// Same pointer rules as [`uor_addr_json`]; `out_label` must be writable
// for at least `UOR_ADDR_MAX_LABEL_BYTES` bytes.
int32_t uor_addr_xml_with_hash(uint8_t algo,
                               const uint8_t *input,
                               uintptr_t input_len,
                               uint8_t *out_label,
                               uintptr_t out_label_len,
                               uintptr_t *out_written);

// asn1 realization with a caller-selected σ-axis (`UOR_ADDR_HASH_*`).
//
// # Safety
//
// Same pointer rules as [`uor_addr_json`]; `out_label` must be writable
// for at least `UOR_ADDR_MAX_LABEL_BYTES` bytes.
int32_t uor_addr_asn1_with_hash(uint8_t algo,
                                const uint8_t *input,
                                uintptr_t input_len,
                                uint8_t *out_label,
                                uintptr_t out_label_len,
                                uintptr_t *out_written);

// ring realization with a caller-selected σ-axis (`UOR_ADDR_HASH_*`).
//
// # Safety
//
// Same pointer rules as [`uor_addr_json`]; `out_label` must be writable
// for at least `UOR_ADDR_MAX_LABEL_BYTES` bytes.
int32_t uor_addr_ring_with_hash(uint8_t algo,
                                const uint8_t *input,
                                uintptr_t input_len,
                                uint8_t *out_label,
                                uintptr_t out_label_len,
                                uintptr_t *out_written);

// codemodule realization with a caller-selected σ-axis (`UOR_ADDR_HASH_*`).
//
// # Safety
//
// Same pointer rules as [`uor_addr_json`]; `out_label` must be writable
// for at least `UOR_ADDR_MAX_LABEL_BYTES` bytes.
int32_t uor_addr_codemodule_with_hash(uint8_t algo,
                                      const uint8_t *input,
                                      uintptr_t input_len,
                                      uint8_t *out_label,
                                      uintptr_t out_label_len,
                                      uintptr_t *out_written);

// cbor realization with a caller-selected σ-axis (`UOR_ADDR_HASH_*`).
//
// # Safety
//
// Same pointer rules as [`uor_addr_json`]; `out_label` must be writable
// for at least `UOR_ADDR_MAX_LABEL_BYTES` bytes.
int32_t uor_addr_cbor_with_hash(uint8_t algo,
                                const uint8_t *input,
                                uintptr_t input_len,
                                uint8_t *out_label,
                                uintptr_t out_label_len,
                                uintptr_t *out_written);

// Free a Grounded handle. Calling with a null pointer is a no-op.
// After this call returns, `handle` is invalid; any further use is
// undefined behaviour.
//
// # Safety
//
// `handle` must be either null or a pointer previously returned by
// any `uor_addr_<realization>_with_witness` call. Each handle must
// be freed exactly once.
void uor_addr_grounded_free(struct UorAddrGrounded *handle);

// Read the κ-label this Grounded carries into `out_label`. Returns
// the number of bytes written (always 71 on success) via
// `out_written` (may be NULL).
//
// # Safety
//
// - `handle` must be a valid live handle returned by a
//   `*_with_witness` call.
// - `out_label` must be writable for at least `out_label_len` bytes.
// - `out_written` if non-null must point to a writable `size_t`.
int32_t uor_addr_grounded_kappa_label(const struct UorAddrGrounded *handle,
                                      uint8_t *out_label,
                                      uintptr_t out_label_len,
                                      uintptr_t *out_written);

// Read the 32-byte SHA-256 content fingerprint into `out_digest`.
//
// # Safety
//
// Same as [`uor_addr_grounded_kappa_label`], with `out_digest`
// writable for at least 32 bytes.
int32_t uor_addr_grounded_content_fingerprint(const struct UorAddrGrounded *handle,
                                              uint8_t *out_digest,
                                              uintptr_t out_digest_len,
                                              uintptr_t *out_written);

// Verify the witness by re-certifying its owned replay trace through
// `prism::replay::certify_from_trace` (via
// [`uor_addr::AddressWitness::verify`]) and writing the recovered
// κ-label into `out_label`. SHA-256 is **not** re-invoked.
//
// On `UOR_ADDR_OK` the bytes in `out_label[..71]` are byte-identical
// to those `uor_addr_grounded_kappa_label` would write (QS-05 replay
// equivalence; CL-R\* in CONFORMANCE.md).
//
// # Safety
//
// Same as [`uor_addr_grounded_kappa_label`].
int32_t uor_addr_grounded_verify(const struct UorAddrGrounded *handle,
                                 uint8_t *out_label,
                                 uintptr_t out_label_len,
                                 uintptr_t *out_written);

// JSON realization, returning a verifiable witness handle.
//
// # Safety
//
// - `input` must be null (with `input_len == 0`) or readable for
//   `input_len` bytes.
// - `out_handle` must be a valid writable pointer to a
//   `*mut UorAddrGrounded`.
int32_t uor_addr_json_with_witness(const uint8_t *input,
                                   uintptr_t input_len,
                                   struct UorAddrGrounded **out_handle);

// S-expression realization, returning a verifiable witness handle.
//
// # Safety
//
// Same as [`uor_addr_json_with_witness`].
int32_t uor_addr_sexp_with_witness(const uint8_t *input,
                                   uintptr_t input_len,
                                   struct UorAddrGrounded **out_handle);

// XML realization, returning a verifiable witness handle.
//
// # Safety
//
// Same as [`uor_addr_json_with_witness`].
int32_t uor_addr_xml_with_witness(const uint8_t *input,
                                  uintptr_t input_len,
                                  struct UorAddrGrounded **out_handle);

// ASN.1 realization, returning a verifiable witness handle.
//
// # Safety
//
// Same as [`uor_addr_json_with_witness`].
int32_t uor_addr_asn1_with_witness(const uint8_t *input,
                                   uintptr_t input_len,
                                   struct UorAddrGrounded **out_handle);

// Ring realization, returning a verifiable witness handle.
//
// # Safety
//
// Same as [`uor_addr_json_with_witness`].
int32_t uor_addr_ring_with_witness(const uint8_t *input,
                                   uintptr_t input_len,
                                   struct UorAddrGrounded **out_handle);

// Code-module realization, returning a verifiable witness handle.
//
// # Safety
//
// Same as [`uor_addr_json_with_witness`].
int32_t uor_addr_codemodule_with_witness(const uint8_t *input,
                                         uintptr_t input_len,
                                         struct UorAddrGrounded **out_handle);

// CBOR realization (RFC 8949 §4.2 + SHA-256), returning a verifiable
// witness handle.
//
// # Safety
//
// Same as [`uor_addr_json_with_witness`].
int32_t uor_addr_cbor_with_witness(const uint8_t *input,
                                   uintptr_t input_len,
                                   struct UorAddrGrounded **out_handle);

// schema.org/Photograph realization, returning a verifiable witness handle.
//
// # Safety
//
// Same as [`uor_addr_json_with_witness`].
int32_t uor_addr_schema_photo_with_witness(const uint8_t *input,
                                           uintptr_t input_len,
                                           struct UorAddrGrounded **out_handle);

// schema.org/Article realization, returning a verifiable witness handle.
//
// # Safety
//
// Same as [`uor_addr_json_with_witness`].
int32_t uor_addr_schema_document_with_witness(const uint8_t *input,
                                              uintptr_t input_len,
                                              struct UorAddrGrounded **out_handle);

// in-toto Statement v1 realization, returning a verifiable witness handle.
//
// # Safety
//
// Same as [`uor_addr_json_with_witness`].
int32_t uor_addr_schema_codemodule_signed_with_witness(const uint8_t *input,
                                                       uintptr_t input_len,
                                                       struct UorAddrGrounded **out_handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* UOR_ADDR_H */
