/* uor-addr-c — C ABI bindings for the uor-addr crate.
* Auto-generated by cbindgen. Do not edit by hand.
*
* Apache-2.0 — https://github.com/UOR-Foundation/uor-addr
*/

#ifndef UOR_ADDR_H
#define UOR_ADDR_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Success.
#define UOR_ADDR_OK 0

// `input == NULL && input_len > 0`, or `out_label == NULL`.
#define UOR_ADDR_ERR_NULL_POINTER -1

// `out_label_len < UOR_ADDR_LABEL_BYTES`.
#define UOR_ADDR_ERR_BUFFER_TOO_SMALL -2

// Input failed the realization's host-boundary parser.
#define UOR_ADDR_ERR_INVALID_INPUT -3

// Input exceeded a typed-input ceiling.
#define UOR_ADDR_ERR_TOO_LARGE -4

// Defensive — substrate-level pipeline failure.
#define UOR_ADDR_ERR_PIPELINE -5

// Verify-error codes — 1:1 with WIT `verify-error` variants. Returned
// by [`uor_addr_grounded_verify`]. All five are *defensive* against
// substrate corruption; unreachable for a handle the C ABI itself
// minted.
#define UOR_ADDR_ERR_VERIFY_EMPTY_TRACE -10

#define UOR_ADDR_ERR_VERIFY_OUT_OF_ORDER_EVENT -11

#define UOR_ADDR_ERR_VERIFY_ZERO_TARGET -12

#define UOR_ADDR_ERR_VERIFY_NON_CONTIGUOUS_STEPS -13

#define UOR_ADDR_ERR_VERIFY_CAPACITY_EXCEEDED -14

// Opaque handle to a Rust-side `AddressOutcome` carrying a sealed
// `Grounded<AddressLabel>` witness. Construct via any of the
// `uor_addr_<realization>_with_witness` functions; release via
// [`uor_addr_grounded_free`].
//
// **Lifetime**: the handle is valid until `uor_addr_grounded_free`
// is called. Calling any `uor_addr_grounded_*` accessor on a freed
// handle is undefined behaviour. The witness lives only in the
// process that minted it — there is no cross-process serialization
// (the underlying `Trace<256>` constructor is `pub(crate)` in
// `uor-foundation`).
typedef struct UorAddrGrounded {
  AddressOutcome outcome;
} UorAddrGrounded;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Wire-format κ-label byte width — `len("sha256:") + 64`.
extern const uintptr_t UOR_ADDR_LABEL_BYTES;

// JSON realization (RFC 8785 JCS + Unicode NFC + SHA-256).
//
// # Safety
//
// - `input` must be null (with `input_len == 0`) or readable for
//   `input_len` bytes.
// - `out_label` must be writable for at least `out_label_len` bytes.
// - `out_written` if non-null must point to a writable `size_t`.
int32_t uor_addr_json(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// S-expression realization (Rivest 1997 canonical form + SHA-256).
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_sexp(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// XML realization (W3C XML-C14N 1.1 subset + SHA-256).
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_xml(const uint8_t *input,
                     uintptr_t input_len,
                     uint8_t *out_label,
                     uintptr_t out_label_len,
                     uintptr_t *out_written);

// ASN.1 realization (ITU-T X.690 DER + SHA-256).
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_asn1(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// Ring realization (UOR-Framework Amendment 43 §2 + SHA-256).
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_ring(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// Code-module realization (CCMAS canonical AST + SHA-256).
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_codemodule(const uint8_t *input,
                            uintptr_t input_len,
                            uint8_t *out_label,
                            uintptr_t out_label_len,
                            uintptr_t *out_written);

// schema.org/Photograph descendant — admits only schema.org/Photograph
// JSON-LD inputs; routes canonical form through the JSON realization.
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_schema_photo(const uint8_t *input,
                              uintptr_t input_len,
                              uint8_t *out_label,
                              uintptr_t out_label_len,
                              uintptr_t *out_written);

// schema.org/Article descendant — admits only schema.org/Article
// JSON-LD inputs (plus subtypes); routes canonical form through JSON.
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_schema_document(const uint8_t *input,
                                 uintptr_t input_len,
                                 uint8_t *out_label,
                                 uintptr_t out_label_len,
                                 uintptr_t *out_written);

// in-toto Statement v1 descendant — admits only in-toto Statement v1
// JSON envelopes (sigstore / SLSA / SCAI / SPDX SBOM predicates).
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_schema_codemodule_signed(const uint8_t *input,
                                          uintptr_t input_len,
                                          uint8_t *out_label,
                                          uintptr_t out_label_len,
                                          uintptr_t *out_written);

// Free a Grounded handle. Calling with a null pointer is a no-op.
// After this call returns, `handle` is invalid; any further use is
// undefined behaviour.
//
// # Safety
//
// `handle` must be either null or a pointer previously returned by
// any `uor_addr_<realization>_with_witness` call. Each handle must
// be freed exactly once.
void uor_addr_grounded_free(struct UorAddrGrounded *handle);

// Read the κ-label this Grounded carries into `out_label`. Returns
// the number of bytes written (always 71 on success) via
// `out_written` (may be NULL).
//
// # Safety
//
// - `handle` must be a valid live handle returned by a
//   `*_with_witness` call.
// - `out_label` must be writable for at least `out_label_len` bytes.
// - `out_written` if non-null must point to a writable `size_t`.
int32_t uor_addr_grounded_kappa_label(const struct UorAddrGrounded *handle,
                                      uint8_t *out_label,
                                      uintptr_t out_label_len,
                                      uintptr_t *out_written);

// Read the 32-byte SHA-256 content fingerprint into `out_digest`.
//
// # Safety
//
// Same as [`uor_addr_grounded_kappa_label`], with `out_digest`
// writable for at least 32 bytes.
int32_t uor_addr_grounded_content_fingerprint(const struct UorAddrGrounded *handle,
                                              uint8_t *out_digest,
                                              uintptr_t out_digest_len,
                                              uintptr_t *out_written);

// Verify the witness by replaying its derivation through
// `prism_verify::certify_from_trace` and writing the recovered
// κ-label into `out_label`. SHA-256 is **not** re-invoked.
//
// On `UOR_ADDR_OK` the bytes in `out_label[..71]` are byte-identical
// to those `uor_addr_grounded_kappa_label` would write (QS-05 replay
// equivalence; CL-R\* in CONFORMANCE.md).
//
// # Safety
//
// Same as [`uor_addr_grounded_kappa_label`].
int32_t uor_addr_grounded_verify(const struct UorAddrGrounded *handle,
                                 uint8_t *out_label,
                                 uintptr_t out_label_len,
                                 uintptr_t *out_written);

// JSON realization, returning a verifiable witness handle.
//
// # Safety
//
// - `input` must be null (with `input_len == 0`) or readable for
//   `input_len` bytes.
// - `out_handle` must be a valid writable pointer to a
//   `*mut UorAddrGrounded`.
int32_t uor_addr_json_with_witness(const uint8_t *input,
                                   uintptr_t input_len,
                                   struct UorAddrGrounded **out_handle);

// S-expression realization, returning a verifiable witness handle.
//
// # Safety
//
// Same as [`uor_addr_json_with_witness`].
int32_t uor_addr_sexp_with_witness(const uint8_t *input,
                                   uintptr_t input_len,
                                   struct UorAddrGrounded **out_handle);

// XML realization, returning a verifiable witness handle.
//
// # Safety
//
// Same as [`uor_addr_json_with_witness`].
int32_t uor_addr_xml_with_witness(const uint8_t *input,
                                  uintptr_t input_len,
                                  struct UorAddrGrounded **out_handle);

// ASN.1 realization, returning a verifiable witness handle.
//
// # Safety
//
// Same as [`uor_addr_json_with_witness`].
int32_t uor_addr_asn1_with_witness(const uint8_t *input,
                                   uintptr_t input_len,
                                   struct UorAddrGrounded **out_handle);

// Ring realization, returning a verifiable witness handle.
//
// # Safety
//
// Same as [`uor_addr_json_with_witness`].
int32_t uor_addr_ring_with_witness(const uint8_t *input,
                                   uintptr_t input_len,
                                   struct UorAddrGrounded **out_handle);

// Code-module realization, returning a verifiable witness handle.
//
// # Safety
//
// Same as [`uor_addr_json_with_witness`].
int32_t uor_addr_codemodule_with_witness(const uint8_t *input,
                                         uintptr_t input_len,
                                         struct UorAddrGrounded **out_handle);

// schema.org/Photograph realization, returning a verifiable witness handle.
//
// # Safety
//
// Same as [`uor_addr_json_with_witness`].
int32_t uor_addr_schema_photo_with_witness(const uint8_t *input,
                                           uintptr_t input_len,
                                           struct UorAddrGrounded **out_handle);

// schema.org/Article realization, returning a verifiable witness handle.
//
// # Safety
//
// Same as [`uor_addr_json_with_witness`].
int32_t uor_addr_schema_document_with_witness(const uint8_t *input,
                                              uintptr_t input_len,
                                              struct UorAddrGrounded **out_handle);

// in-toto Statement v1 realization, returning a verifiable witness handle.
//
// # Safety
//
// Same as [`uor_addr_json_with_witness`].
int32_t uor_addr_schema_codemodule_signed_with_witness(const uint8_t *input,
                                                       uintptr_t input_len,
                                                       struct UorAddrGrounded **out_handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* UOR_ADDR_H */
