/* uor-addr-c — C ABI bindings for the uor-addr crate.
* Auto-generated by cbindgen. Do not edit by hand.
*
* Apache-2.0 — https://github.com/UOR-Foundation/uor-addr
*/

#ifndef UOR_ADDR_H
#define UOR_ADDR_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Success.
#define UOR_ADDR_OK 0

// `input == NULL && input_len > 0`, or `out_label == NULL`.
#define UOR_ADDR_ERR_NULL_POINTER -1

// `out_label_len < UOR_ADDR_LABEL_BYTES`.
#define UOR_ADDR_ERR_BUFFER_TOO_SMALL -2

// Input failed the realization's host-boundary parser.
#define UOR_ADDR_ERR_INVALID_INPUT -3

// Input exceeded a typed-input ceiling.
#define UOR_ADDR_ERR_TOO_LARGE -4

// Defensive — substrate-level pipeline failure.
#define UOR_ADDR_ERR_PIPELINE -5

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Wire-format κ-label byte width — `len("sha256:") + 64`.
extern const uintptr_t UOR_ADDR_LABEL_BYTES;

// JSON realization (RFC 8785 JCS + Unicode NFC + SHA-256).
//
// # Safety
//
// - `input` must be null (with `input_len == 0`) or readable for
//   `input_len` bytes.
// - `out_label` must be writable for at least `out_label_len` bytes.
// - `out_written` if non-null must point to a writable `size_t`.
int32_t uor_addr_json(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// S-expression realization (Rivest 1997 canonical form + SHA-256).
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_sexp(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// XML realization (W3C XML-C14N 1.1 subset + SHA-256).
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_xml(const uint8_t *input,
                     uintptr_t input_len,
                     uint8_t *out_label,
                     uintptr_t out_label_len,
                     uintptr_t *out_written);

// ASN.1 realization (ITU-T X.690 DER + SHA-256).
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_asn1(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// Ring realization (UOR-Framework Amendment 43 §2 + SHA-256).
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_ring(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// Code-module realization (CCMAS canonical AST + SHA-256).
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_codemodule(const uint8_t *input,
                            uintptr_t input_len,
                            uint8_t *out_label,
                            uintptr_t out_label_len,
                            uintptr_t *out_written);

// schema.org/Photograph descendant — admits only schema.org/Photograph
// JSON-LD inputs; routes canonical form through the JSON realization.
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_schema_photo(const uint8_t *input,
                              uintptr_t input_len,
                              uint8_t *out_label,
                              uintptr_t out_label_len,
                              uintptr_t *out_written);

// schema.org/Article descendant — admits only schema.org/Article
// JSON-LD inputs (plus subtypes); routes canonical form through JSON.
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_schema_document(const uint8_t *input,
                                 uintptr_t input_len,
                                 uint8_t *out_label,
                                 uintptr_t out_label_len,
                                 uintptr_t *out_written);

// in-toto Statement v1 descendant — admits only in-toto Statement v1
// JSON envelopes (sigstore / SLSA / SCAI / SPDX SBOM predicates).
//
// # Safety
//
// Same pointer-validity requirements as [`uor_addr_json`].
int32_t uor_addr_schema_codemodule_signed(const uint8_t *input,
                                          uintptr_t input_len,
                                          uint8_t *out_label,
                                          uintptr_t out_label_len,
                                          uintptr_t *out_written);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* UOR_ADDR_H */
